// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnAGY3zqBbdB_FBwu10uz0wyfg06KiIE4',
    appId: '1:963831388420:web:9cf2a4e0fcf2cd987cd851',
    messagingSenderId: '963831388420',
    projectId: 'fanisfun-test',
    authDomain: 'fanisfun-test.firebaseapp.com',
    storageBucket: 'fanisfun-test.appspot.com',
    measurementId: 'G-VFVMFBQMS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3hxsoFoV9tsIrm83PYORA04uFWHvfW3E',
    appId: '1:963831388420:android:12dc7c60f254ba497cd851',
    messagingSenderId: '963831388420',
    projectId: 'fanisfun-test',
    storageBucket: 'fanisfun-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKrZ-mJ-i9D2P0ODRukMvb8J45SVmKQAU',
    appId: '1:963831388420:ios:ccdee1578e8ab1457cd851',
    messagingSenderId: '963831388420',
    projectId: 'fanisfun-test',
    storageBucket: 'fanisfun-test.appspot.com',
    iosClientId: '963831388420-qe5lc368qmjnfse68u57bombf4vitl60.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseExampleApp',
  );
}
